### ISSUE TITLE
Ops * July Tasks

### ISSUE THREAD

**Issue by Chethan-mr** [Chethan-mr/mentorskool#2]
**Cohort 1**

- [x] Pyspark foundations Problem Solving VILT  Zoom Recording Upload  1st July 
- [x] Knowledge-Check - 2 Deployment 2nd July by 10 AM
- [x] Cloud Fundamentals Zoom Recording Upload 2nd July
- [x] Cloud Fundamentals Deployment 3rd July 
- [x] Cloud Fundamentals Deployment 4th July
- [x] do select questions for KC3
- [x] Data Landscape on Cloud  Zoom Recording Upload  5th July
- [x] Knowledge-Check - 3  Deployment 6th July by 10 AM 
- [x] Hands on progress 
- [x] Attendance 
- [x] sending zoom links

**Cohort 2**

- [x] Problem Solving Excel VILT  Zoom Recording Upload  1st July 
- [x] Data Wrangling -1 Deployment 2nd July
- [x] Release  Assessment - 3 from DoSelect - 3rd July - 10 AM.
- [x] SQL Problem Solving Zoom Recording Upload  4th July
- [x] Data Wrangling - 2 Deployment 4th July
- [x] Retest of Assessment - 1 from DoSelect - 6th July - 10 AM
- [x] Attendance 
- [x] Hands on progress
- [x] sending zoom links 

**Snowflake Advance -July batch**

- [x] ILT-1-Data Ingestion in Snowflake Zoom Recording Upload  1st July 
- [x]  Masterclass on ILT-1-Data Ingestion in Snowflake deployment 1st July
- [x] ILT-Functions & Views in Snowflake Zoom Recording Upload  3rd July 
- [x] Release Partial Mock Test - 1 Assessment 5th by 10 AM
- [x] Attendance

**Comment by Ayushii94** [comment]
**Cohort 1**

- [x] analysis of assessment 6
- [x] analysis of knowledge check 2
- [x] release feedback form in VILT for module 7 - July 1
- [x] release feedback form in VILT for module 8 - July 5


**Cohort 2**

- [x] analysis of assessment 2
- [x] analysis of assessment 3
- [x] release feedback form in VILT for module 3 - July 1
- [x] record hands-on progress pivot creation - 1 video {please take Mandar's help if he's available}
- [x] record hands-on sheet update - 1 video

**Comment by Chethan-mr** [comment]
**Ops * July 2 nd Week Tasks**


**Cohort 1:**

- [x] Data Science LandScape + Introduction to ML Zoom Recording Upload 8-Jul.
- [x] Deploy Data Science LandScape + Introduction bu 11 AM 
- [x] Analysis of Knowledge Check 3 8th Jul.
- [x] Data Science LandScape + Introduction to ML Zoom Recording Upload 9-Jul.
- [x]  Release Feedback from in VILT for Module 9 - 9-Jul.
- [x] Upload Knowledge Check Questions to Do select 9-Jul.
- [x] Release cohort one partice test by fast half 11th.
- [x] Analysis of reassement 6 
- [x] Analysis Hands on progress 11-Jul.
- [x] Release  Knowledge-Check - 4 11-Jul. 
- [x] Analysis of Knowledge-Check 4 12-Jul.

**Cohort 2:**

- [x] Analysis of Re test Assessment-1 8-Jul.
- [x] Reassessment-2 of cohort 2 8-Jul.
- [x] Deploy Data Moduling  by 10:00 AM 9th Jul.
- [x] Problem Solving  Zoom Recording Upload 9-Jul.
- [x] Analysis of Reassessment-2 9 - Jul.
- [x] Analysis of Hands on 10-Jul.
- [x] Relational Data Modelling Zoom Recording Upload 10-Jul.
- [x] deploy for hands on 
- [x] deployment of python program 11th .
- [x] Release Feeback from in VILT for Module 4 11-Jul
- [x] Analysis Hands on progress 11-Jul.
- [x] Problem Solving Zoom Recording Upload 11-Jul.
- [x] Programming Fundamentals Solving Zoom Recording Upload 12-Jul.
- [x] Deploy Assessment - 4 on 13 Jul by 10 AM.
- [x] Create Zoom link for the week by 6:00 PM 12-Jul.

**Snowflake Advance July:**

- [x] ILT-Performance Concepts Zoom Recording Upload 8-Jul.
- [x] ILT-Change Data Capture in Snowflake Zoom Recording Upload 9-Jul.
- [x] ILT-Clustering in Snowflake Zoom Recording Upload 10-Jul.
- [x] Create Zoom link for the week by 6:00 PM 12-Jul.
- [x] Updating Comprenssive attendance.

**Comment by Chethan-mr** [comment]
**Ops 3 WEEK TASKS** 


**Cohort 1:**

- [x] Hands-on practice release 15th Jul by 10 AM.
- [x] hands on progress 
- [x] Comprehensive Exam Practice 2 – Coding VILT recording upload 16th Jul by 2PM.
- [x] Hands-on practice Release 17th Jul by 10 AM.
- [x] Doubt Clarification VILT reccording Upload 18th Jul 2 PM.
- [x] Analysis of Hands on Progress .

**Cohort 2:** 

- [x] Deployment for Basic Programming constructs of Python on 15th Jul by 10 AM.
- [x] Analysis of assessment 4  15th Jul.
- [x] Release Retest of Assessment - 3 from Do select on 15th Jul by 10 AM.
- [x] Deployment fo Basic Programming constructs of Python on 16th Jul.
- [x] Retest Assement -3 Analysis on 16th.
- [x] Create Deployment plan sheet  
- [x] Basic Programming constructs of Python VLIT Recording Upload 8 PM.
- [x] Hands-On release on 17th Jul.
- [x] Deployment Data types and Data Structures on 17th Jul 10 AM.
- [x] Problem Solving VILT Upload 18th Jul
- [x] hands  on release 18th july .
- [x] Introduction to Debugging VILT upload 19th Jul.
- [x] Hands on release 
- [x] Problem Solving VILT Upload 20th july.
- [x] Attendance 
- [x] hands on progress 
- [x] Zoom links for next week 

**Snowpro Adv July:**

- [x] Upload ILT-Performance Concepts 2.
- [x] Partial Mock Test - 2 Release by 10 AM 16th July.
- [x] ILT-Caching & Data Protection Recording Upload by 18 th July.
- [x]  ILT-System Functions in Snowflake Recording Upload by 19 th July

Program Folder 

- [x] Create Program Folder for Databricks July Batch.
- [x]  Create Program Folder for Snowflake July Batch.

**Comment by Chethan-mr** [comment]
**Ops 4  WEEK TASKS**

**Cohort 2**

- [x] Deployment of self placed module Python Data Wrangling 22-07-2024 by 09:00 AM link [here](https://www.app.enqurious.com/projects/62ef7819-8fda-48dd-a0cc-862a88d595fb) 
- [x] Hands on progress by 22-07-2024 6 PM.
- [x] Retest of Assessment - 4 on 22-07-2024 by 10 AM.
- [x] Retest of Assessment -4 Analysis 23-07-2024 .
- [x] VILT Zoom recording upload 24-07-2024 by 8:30 PM.
- [x] VILT Zoom recording upload 26-07-2024 by 8:30 PM 
- [x] Assessment - 5 on 27-07-2024 by 10 AM.
- [x] Assessment -5 analysis by 28-07-2024 .

**Snowflake Adv** 

- [x] VILT Zoom recording upload by 22-07-2024 6:00 PM.
- [x] VILT Zoom recording upload by 23-07-2024 6:00 PM.
- [x] Partial Mock Test - 3 deployment 24-07-2024 10:00 AM.
- [x] Upload VILT Recording for 25 th July.
- [x] Full Length Mock Test - 1 deployment 29-07-2024 10:00 AM.
- [x] Comprehensive attendance update  

**Databricks LAT July**  

- [x] Deployment plan 
- [x] VILT Zoom recording Upload by 24-07-2024.
- [x] TRED-LAT-DB-19072024_Need for Databricks Deployment by 25-07-2024 by 9:00 AM.
- [x] VILT Zoom recording Upload by 26-07-2024.
- [x] TRED-LAT-DB-19072024_PS-Data analysis-1  Deployment by 27-07-2024 by 9:00 AM.
- [x] VILT Zoom recording Upload by 27-07-2024.
- [x] Attendance 
- [x] hands on progress 
- [x] zoom recordings for next week .

**Snowflake LAT  July** 

- [x] Zoom recording upload for 25th July.
- [x] Deployment Snowflake Architecture Practice Set 25th July.
- [x] Deployment plan .
- [x] attendance .
- [x] Program Progress.

**Comment by Chethan-mr** [comment]
**August 1st  Week Ops Tasks** 

**Cohort 2 :**

- [x] Data Cleansing and Preparation deployment on 29  th 10 am .
- [x] Hands on Progress by 29 th 6 PM.
- [x] Proctoring Analysis of Assessment 5.
- [x] Problem Solving VILT Recording Upload 29th Jul.
- [x] Data Visualization and Interpretation Recording upload 30 th Jul .
- [x] Data Visualization and Interpretation Deployment on 31st Jul 10 am .
- [x] Feedback Form release on session.
- [x] Hands on Progress by 31st  6 PM.
- [x] Problem Solving VILT Recording Upload 31 Jul .
- [x] Distributed Computing and Pyspark Introduction   VILT Recording Upload 1 St Aug.
- [x] 3 API of Pyspark Deployment 1 st Aug 10 am.
- [x] Hands on Progress 1 st Aug   6 PM.
- [x] Problem Solving  VILT Recording Upload 2nd Aug.
- [x] Assessment - 6  deployment from Do select 3 rd Aug 10 am.
- [x] Attendance 
- [x] Zoom Links for next week.

**Snowpro Advance Batch** 

- [x] Full Length Mock Test - 1 on 30th .
- [x] Full Length Mock Test - 2 on 2nd Aug.
- [ ] Full Length Mock Test - 3 on 5 th.

**Snowflake July Batch** 

- [x] Copy Options in Snowflake VILT Recording Upload  29 th .
- [x] Types of Tables VILT Recording Upload 30 th..
- [x] Partial Mock Test - 1  on 1 st 10 am.
- [x] Streams and Scheduling Tasks VILT Recording Upload on 2 nd .
- [x] Attendance 
- [x] Program Progress 
- [x] Zoom Links for next week.

**Databricks July Batch** 

- [x] Hands On release 29th by 10 am.
- [x] Data Analysis using Databricks - 2 VILT Recording Upload on 30th .
- [x] Hands On release 31st by 10 am.
- [x] Partial Mock Test - 1 on 1 st 10 am.
- [x] Introduction to ETL VILT Recording Upload on 2nd July.
- [x] Program Progress 
- [x] Attendance
- [x] Zoom links for Next week.
